### Site Settings ###
title       : Rafael Ribeiro
keywords    : Topics in Devops, Terraform, AWS, CI/CD. 
description : Welcome! here I will share articles related to devops and programming in general. 
baseurl     : ""     
repository  : rribeiro1/rribeiro1.github.io
remote_theme: rribeiro1/jekyll-theme

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  
### Author Info ###
author:
  name              : Ribeiro
  image             : photo.png
# behance           : your_username
# dribbble          : your_username
  email             : rafael.pr10@gmail.com
# facebook          : your_username
  github            : rribeiro1
# gitlab            : your_username
  instagram         : rafprib
  linkedin          : rribeiro10
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
  stackoverflow     : 7690356
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name

### Disqus ###
disqus: rribeiro1-github-io

### Analytics ###
analytics:
  enabled: true  # Set false to disable analytics feature
  google:
    tracking_id: UA-163302221-1 # your google analytics tracking-id

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
